//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int CirculationID { get; set; }
        public string Year { get; set; }
        public int BookID { get; set; }
        public int CirculationSubTypeID { get; set; }
        public Nullable<int> PrintCirculation { get; set; }
        public Nullable<int> DigitalReplicaCirculation { get; set; }
        public Nullable<int> DigitalNonReplicaCirculation { get; set; }
        public int VersionID { get; set; }
        public System.DateTime Load_Date { get; set; }
    }
}
