//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumDiscountRate
    {
        public int PremiumDiscountRateID { get; set; }
        public string Year { get; set; }
        public int BookID { get; set; }
        public Nullable<decimal> AdvertorialEarnedPercentDiscount { get; set; }
        public Nullable<decimal> BleedOpenPercentPremium { get; set; }
        public Nullable<decimal> BleedEarnedPercentPremium { get; set; }
        public Nullable<decimal> Cover2OpenPercentPremium { get; set; }
        public Nullable<decimal> Cover2EarnedPercentPremium { get; set; }
        public Nullable<decimal> Cover3OpenPercentPremium { get; set; }
        public Nullable<decimal> Cover3EarnedPercentPremium { get; set; }
        public Nullable<decimal> Cover4OpenPercentPremium { get; set; }
        public Nullable<decimal> Cover4EarnedPercentPremium { get; set; }
        public Nullable<decimal> FracHalfPageOpenPercentPremium { get; set; }
        public Nullable<decimal> FracHalfPageEarnedPercentPremium { get; set; }
        public Nullable<decimal> FracThirdPageOpenPercentPremium { get; set; }
        public Nullable<decimal> FracThirdPageEarnedPercentPremium { get; set; }
        public Nullable<decimal> FracThirdRunOppFBPOpenPercentPremium { get; set; }
        public Nullable<decimal> FracThirdRunOppFBPEarnedPercentPremium { get; set; }
        public Nullable<decimal> SpreadC2P1EarnedPercentDiscount { get; set; }
        public Nullable<decimal> SpreadROBEarnedPercentDiscount { get; set; }
        public Nullable<int> FifthColorMetallicOpenDollarPremium { get; set; }
        public Nullable<int> FifthColorMetallicEarnedDollarPremium { get; set; }
        public Nullable<int> FifthColorMatchOpenDollarPremium { get; set; }
        public Nullable<int> FifthColorMatchEarnedDollarPremium { get; set; }
        public Nullable<int> FifthColorPMSOpenDollarPremium { get; set; }
        public Nullable<int> FifthColorPMSEarnedDollarPremium { get; set; }
        public int VersionID { get; set; }
        public System.DateTime Load_Date { get; set; }
    }
}
