//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabletRate
    {
        public int TabletRateID { get; set; }
        public string Year { get; set; }
        public int BookID { get; set; }
        public int TabletFunctionalityID { get; set; }
        public Nullable<int> OpenRate { get; set; }
        public Nullable<int> EarnedRate { get; set; }
        public int VersionID { get; set; }
        public System.DateTime Load_Date { get; set; }
    }
}
